name: Go Static Analysis

on:
  push:
    branches:
      - v2.x
  pull_request:
    branches:
      - v2.x

jobs:
  golangci:
    name: nilaway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: install nilaway
        run: go install go.uber.org/nilaway/cmd/nilaway@latest

      - name: nilaway
        run: ~/go/bin/nilaway ./...
        continue-on-error: true